name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 프로젝트에서 사용하는 Node.js 버전에 맞게 수정하세요

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -v -o StrictHostKeyChecking=no -i private_key -r dist package.json package-lock.json ${USER}@${HOST}:~/to102-BE/
        ssh -v -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          set -x
          cd ~/to102-BE
          if [ ! -d "node_modules" ]; then
            npm ci --only=production
          fi
          npm install pm2 -g
          pm2 describe to102-BE > /dev/null
          if [ $? -eq 0 ]; then
            pm2 restart to102-BE
          else
            pm2 start npm --name "to102-BE" -- start
          fi
          pm2 save
        '

    - name: Verify Deployment
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          pm2 list
          curl -f http://localhost:3000 || echo "Application is not responding on port 3000"
        '
