name: Deploy to EC2 test

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Debug Information
        run: |
          echo "Debugging connection to EC2"
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER: ${{ secrets.EC2_USER }}"

      - name: Test Network Connection
        run: |
          telnet ${{ secrets.EC2_HOST }} 22

      - name: Debug SSH Connection
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -v -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          scp -i private_key -r dist package*.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/to102-BE/
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd ~/to102-BE
            npm ci --only=production
            pm2 restart to102-BE || pm2 start npm --name "to102-BE" -- run start:prod
            pm2 save
          '

      - name: Verify Deployment
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd ~/to102-BE
            echo "Current directory: $(pwd)"
            echo "Files in directory:"
            ls -la
            echo "PM2 processes:"
            pm2 list
            echo "Application response:"
            curl -sSf http://localhost:3000 || echo "Application is not responding on port 3000"
          '

      - name: Clean up
        run: rm -f private_key
