name: Deploy to EC2 testing

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 저장소의 최신 커밋을 가져옵니다.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 모든 커밋을 가져옵니다.

      # Node.js 설정
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 의존성 캐싱
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      # 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 빌드
      - name: Build
        run: npm run build

      # 디버깅 정보 출력
      - name: Debug Information
        run: |
          echo "Debugging connection to EC2"
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "EC2_USER: ${{ secrets.EC2_USER }}"

      # SSH 연결 디버깅
      - name: Debug SSH Connection
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -vvv -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "SSH connection successful"'

      # 배포 전에 최신 커밋을 원격 서버로 가져옵니다.
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd ~/to102-BE &&
            git pull origin main &&
            npm ci --only=production &&
            pm2 delete to102-BE || true &&
            pm2 start npm --name "to102-BE" -- run start:prod &&
            pm2 save
          '

      # 배포 확인
      - name: Verify Deployment
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd ~/to102-BE
            echo "Current directory: $(pwd)"
            echo "Files in directory:"
            ls -la
            echo "PM2 processes:"
            pm2 list
            echo "Application response:"
            curl -sSf http://localhost:3000 || echo "Application is not responding on port 3000"
          '

      # 임시 파일 정리
      - name: Clean up
        run: rm -f private_key
